### ISSUE TITLE
yo sean there is a file missing

### ISSUE THREAD

**Issue by fopsdev** [MangoTools/generator-sean#2]
hi there

i've just installed sean generator and after the step where the angular libs can be selected i get this exception: 

...
Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/generator-sean/app/templates/app/models/user.server.model.js'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at _prepCopy (/usr/local/lib/node_modules/generator-sean/node_modules/yeoman-generator/lib/actions/actions.js:51:13)
    at copy (/usr/local/lib/node_modules/generator-sean/node_modules/yeoman-generator/lib/actions/actions.js:79:19)
    at yeoman.generators.Base.extend.copyApplicationFolder (/usr/local/lib/node_modules/generator-sean/app/index.js:117:8)
    at /usr/local/lib/node_modules/generator-sean/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback](timers.js:345:15)
...

hope that helps

**Comment by adidoo** [comment]
Hi, 
You're right,
this should not be there. line 117 of app/index.js.

Fixed

Thank's
