### ISSUE TITLE
Fresh Install - Getting an error cannot add article.

### ISSUE THREAD

**Issue by countrdd** [MangoTools/generator-sean#6]
I am getting this on the client side on a fresh install. 

ReferenceError: $rootScope is not defined
    at new <anonymous> (http://localhost:3000/modules/articles/controllers/articles.client.controller.js:10:7)
    at invoke (http://localhost:3000/lib/angular/angular.js:3965:17)
    at Object.instantiate (http://localhost:3000/lib/angular/angular.js:3976:23)
    at http://localhost:3000/lib/angular/angular.js:7315:28
    at http://localhost:3000/lib/angular/angular.js:6711:34
    at forEach (http://localhost:3000/lib/angular/angular.js:332:20)
    at nodeLinkFn (http://localhost:3000/lib/angular/angular.js:6698:11)
    at compositeLinkFn (http://localhost:3000/lib/angular/angular.js:6146:13)
    at publicLinkFn (http://localhost:3000/lib/angular/angular.js:6042:30)
    at http://localhost:3000/lib/angular-ui-router/release/angular-ui-router.js:3905:9 <section data-ui-view="" class="ng-scope">

**Comment by countrdd** [comment]
public/modules/articles/config/articles.client.routes.js
      7 |        var access = roleManager.accessLevels;
                              ^ 'roleManager' is not defined.
   public/modules/articles/controllers/articles.client.controller.js
     10 |      $rootScope.$on('Auth',function(){
               ^ '$rootScope' is not defined.
   public/modules/core/config/core.client.routes.js
     10 |        var access = roleManager.accessLevels;
                              ^ 'roleManager' is not defined.
   public/modules/core/controllers/home.client.controller.js
      8 |        $scope.user = User.get();
                               ^ 'User' is not defined.
     11 |        $rootScope.$on('Auth',function(){
                 ^ '$rootScope' is not defined.
     12 |            $scope.user = User.get();
                                   ^ 'User' is not defined.

**Comment by dannymac7** [comment]
I've been getting the same error

**Comment by crainj** [comment]
This is still a problem.
